### ISSUE TITLE
Bug found in get_tid.py

### ISSUE THREAD

**Issue by wangtuo0820** [MLProject2018/ML_project#1]
Hi! Your script in get_tid.py line 77-78 may have some error. Because you traverse all the split_ file, but write the result in the same file "../data/tidlist.npy", so later result will cover the previous one. My result in get_apivec has shape (13887, 296), which mean we totally have 13887 different file, and 296 different api. @lisilin013

**Comment by lisilin013** [comment]
Ok, I got it! It's my fault, I feel very shame..... This bug should not be in my code...
Thanks,Big Old!
